### ISSUE TITLE
음..이런건 프라이빗프로젝트로..

### ISSUE THREAD

**Issue by niceaji** [kyungw00k/resume.json#1]
어디가시나요?

**Comment by kyungw00k** [comment]
@niceaji 아뇨 그냥 예전 부터  `함 정리 해 봐야지` 싶어서 정리 해보고 있는데... 빈 프로젝트일 때 `private` 였다가 굳이 또 숨길 필요 까지는 없어서 `public`으로 바꿨습니다 ㅎ
